### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MajerMartin** [wujixiu/helmet-detection#26]
Hello @wujixiu, can you please add LICENSE file to your repository?

I would like to use some of the pretrained models (Squeezenet-SSD and SSD-RPA300) on your dataset but it is not clear what license they are available under. Currently the is no license information which technically means that your repo falls under  "all rights reserved".

**Comment by chouxianyu** [comment]
I also want to ask this question because I want to use this dataset. 
If @wujixiu reply, please @ me.

**Comment by chouxianyu** [comment]
I just found out that the author @wujixiu has created Apache License 2.0 21 days ago, so this issue can be closed!
