### ISSUE TITLE
yolov3-tiny score

### ISSUE THREAD

**Issue by alexkarpxb** [wujixiu/helmet-detection#27]
I downloaded yolov3-tiny_final.weights and yolov3-tiny.cfg and compile model like this

```
helmet_net = cv2.dnn.readNetFromDarknet(
    'cfg/yolov3-tiny.cfg', 'model-weights/yolov3-tiny_final.weights')
helmet_net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
helmet_net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
blob = cv2.dnn.blobFromImage(image, 1 / 255, (416, 416),
                                 [0, 0, 0], 1, crop=False)
helmet_net.setInput(blob)

# Runs the forward pass to get output of the output layers
outs = helmet_net.forward(get_outputs_names(helmet_net))
```

after this I map outs to get only items where confidences are >0.7 and get following result

![result](https://user-images.githubusercontent.com/32259277/80617587-f6bcc200-8a4a-11ea-8a29-977f34a0a1de.jpg)

What can be a problem of this behavior? Actually it didn't find real helmet...

**Comment by wujixiu** [comment]
blob = cv2.dnn.blobFromImage(image, 1 / 255, (416, 416),
                                 [0, 0, 0], 1, crop=False)

try a different mean value instead of [0,0,0].

**Comment by alexkarpxb** [comment]
@wujixiu could you please provide this parameter for yolov3? I tried different values that you provide for another models but It didn't help :( 

```
blob = cv2.dnn.blobFromImage(image, 1/255, (416, 416),
                                 [104, 117, 123], 1, crop=False)
```

![helmet7](https://user-images.githubusercontent.com/32259277/80702444-c11ae600-8ae9-11ea-94eb-b92ec91fafa2.jpg)

**Comment by alexkarpxb** [comment]
There was a trouble in cfg file, I used wrong one, now it's working as expected, thank you

**Comment by zongoalbert** [comment]
@alexkarpxb  hello sir , could you please tell me how can be run this project , the file `README.md` is note clear , please help me
