### ISSUE TITLE
unable to download weight files through Baidu app

### ISSUE THREAD

**Issue by Siddartha123** [wujixiu/helmet-detection#8]
The content is not in english  and unable to download the weight files, can you please provide alternate link to directly download the files?

**Comment by qiuchenqqb** [comment]
Can you please use google drive, because we can't download weight files for some unknown reasons.

**Comment by wujixiu** [comment]
Data and weights are available in [Google Drive](https://drive.google.com/drive/folders/12WtXQyM-7jWvWPtCXZlnycsIK72ClHgu?usp=sharing) Now.

**Comment by Siddartha123** [comment]
Thank you :)
